### PR TITLE
Update MainPartyCommand.php

### PR DESCRIPTION
**Pull request by HypertextPP**

### CODE REVIEW

**Comment by IrishUHC** [comment]
Why was this merged, you combined the description and the usage which breaks the command. Please review your changes and commit.

**Comment by HypertextPP** [comment]
"Breaks the command".

And how do you believe it does that then?

**Comment by HypertextPP** [comment]
The missing argument would break it, yes. But not the extended description.

**Comment by IrishPacks** [comment]
you did not provide any input for the usage.

**Comment by IrishPacks** [comment]
so trying to use an array for a string would break it most certainly.

**Pull request merged**
