### PR TITLE
Added switch method for sub-command examination.

### PR DESCRIPTION
**Pull request by HypertextPP**
Don't mind helping out if you guys want me to. :+1:

### CODE REVIEW

**Comment by IrishUHC** [comment]
we have intentions of adding an api which is why we have $this->plugin->methodNameHere() etc

**Comment by HypertextPP** [comment]
You still need to switch through subcommands...

**Comment by IrishUHC** [comment]
Or, we could not. Reverting changes.

**Comment by Syntaxious** [comment]
We still need to switch through the subcommands, PR is accepted.

**Comment by IrishUHC** [comment]
Subcommands is fine, I'm reverting some of the changes that remove API methods.

**Comment by YaBoiBalAnce** [comment]
Yall should create a interface
`interface SubCommand{
    public function getName();
    public function getDescription();
    public function hasPermission(CommandSender $sender);
    public function execute(array $args, CommandSender $sender);
}`

then extend SubCommand
so you can make it separate classes easier

**Comment by HypertextPP** [comment]
That is a valid method, however, and this is personal preference, switching through subs is a lot more readable and easier. Theoretically, it is also a lot quicker as it doesn't take as much time to process.

**Pull request merged**
